modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="newmod"
version="1.0.0"
displayName="New Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="gusud, MCreator"

[[dependencies.newmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



